// packages/vue-ui/src/components/ReverseGeocodeInput.vue
<script setup lang="ts">
import type { WheraboutsClient } from "@wherabouts/sdk";
import { computed, watch } from "vue";
import { useReverseGeocode } from "../composables/use-reverse-geocode";
import { cn } from "../utils/cn";

const props = withDefaults(
	defineProps<{
		/** Required. SDK client created with `createWheraboutsClient`. */
		client: WheraboutsClient;
		/** Class applied to the input element. */
		class?: string;
		/** Disable the input. */
		disabled?: boolean;
		/** id forwarded to the input element. */
		id?: string;
		/** Latitude to reverse-geocode. */
		latitude: number | null;
		/** Longitude to reverse-geocode. */
		longitude: number | null;
		/** Input placeholder text. */
		placeholder?: string;
	}>(),
	{
		placeholder: "Address will appear here",
	}
);

const emit = defineEmits<{
	(
		e: "result",
		result: { address: string | null; distance: number | null }
	): void;
}>();

const coords = computed(() =>
	props.latitude != null && props.longitude != null
		? { lat: props.latitude, lng: props.longitude }
		: null
);

const { address, distance } = useReverseGeocode(props.client, coords);

watch(
	[address, distance],
	() => {
		emit("result", {
			address: address.value?.formattedAddress ?? null,
			distance: distance.value ?? null,
		});
	},
	{ immediate: true }
);

const displayText = computed(() => address.value?.formattedAddress ?? "");
</script>

<template>
  <input
    :id="props.id"
    :class="cn(
      'block h-8 w-full cursor-default rounded-none border border-input bg-muted/40 px-2.5 py-1 text-foreground text-xs',
      props.class
    )"
    data-slot="geocode-input"
    :disabled="props.disabled"
    :placeholder="props.placeholder"
    readonly
    type="text"
    :value="displayText"
  />
</template>

// packages/react-ui/src/components/reverse-geocode-input.tsx
import { useReverseGeocode } from "@wherabouts/react";
import type { WheraboutsClient } from "@wherabouts/sdk";
import { type ReactNode, useEffect } from "react";
import { cn } from "../utils/cn";

export interface ReverseGeocodeInputProps {
	/** Class applied to the input element. */
	className?: string;
	/** Required. SDK client created with `createWheraboutsClient`. */
	client: WheraboutsClient;
	/** Disable the input. */
	disabled?: boolean;
	/** id forwarded to the input element. */
	id?: string;
	/** Latitude to reverse-geocode. */
	latitude: number | null;
	/** Longitude to reverse-geocode. */
	longitude: number | null;
	/** Result callback, called whenever the resolved address changes. */
	onResult?: (result: {
		address: string | null;
		distance: number | null;
	}) => void;
	/** Input placeholder text. */
	placeholder?: string;
}

export function ReverseGeocodeInput({
	client,
	latitude,
	longitude,
	onResult,
	className,
	disabled,
	placeholder = "Address will appear here",
	id,
}: ReverseGeocodeInputProps): ReactNode {
	const { address, distance } = useReverseGeocode(
		client,
		latitude != null && longitude != null
			? { lat: latitude, lng: longitude }
			: null
	);

	useEffect(() => {
		onResult?.({
			address: address?.formattedAddress ?? null,
			distance: distance ?? null,
		});
	}, [address, distance, onResult]);

	const displayText = address?.formattedAddress ?? "";

	return (
		<input
			className={cn(
				"block h-8 w-full cursor-default rounded-none border border-input bg-muted/40 px-2.5 py-1 text-foreground text-xs",
				className
			)}
			data-slot="geocode-input"
			disabled={disabled}
			id={id}
			placeholder={placeholder}
			readOnly
			type="text"
			value={displayText}
		/>
	);
}
